#!/usr/bin/env bash
# Generate auto-updated docs pages from crate source.
# Called by: `cargo xtask docs` (via Rust) or directly by nix builds.
set -euo pipefail

ROOT="${1:-.}"
OUT="$ROOT/docs/src/generated"
mkdir -p "$OUT"

# ── helpers ──────────────────────────────────────────────────────────────

WARNING='<!-- This file is auto-generated by `cargo xtask docs`. Do not edit. -->

<div class="generated-warning">
⚡ Auto-generated from source. Run <code>cargo xtask docs</code> to refresh.
</div>
'

count_lines() {
    find "$1" -name '*.rs' -not -path '*/target/*' 2>/dev/null \
        | xargs cat 2>/dev/null \
        | wc -l \
        || echo 0
}

count_tests() {
    local n
    n=$(find "$1" -name '*.rs' -not -path '*/target/*' 2>/dev/null \
        | xargs grep -c '#\[test\]\|#\[tokio::test\]' 2>/dev/null \
        | awk -F: '{s+=$2} END {print s+0}') || true
    echo "${n:-0}"
}

crate_doc() {
    local lib="$1/src/lib.rs"
    if [ ! -f "$lib" ]; then echo ""; return; fi
    local lines
    lines=$(sed -n '/^\/\/!/{ s|^//! *||; p; }' "$lib" | head -5) || true
    echo "$lines" | sed '/^$/,$d; /^#/d' | tr '\n' ' ' | sed 's/ *$//'
}

workspace_deps() {
    local toml="$1/Cargo.toml"
    grep '^clankers-' "$toml" 2>/dev/null \
        | sed 's/[^a-zA-Z0-9-].*//' \
        | sort -u \
        || true
}

# ── stats.md ─────────────────────────────────────────────────────────────

generate_stats() {
    local total_loc=0 total_tests=0 crate_count=0
    local tmpfile
    tmpfile=$(mktemp)

    for d in "$ROOT"/crates/*/; do
        [ -d "$d/src" ] || continue
        local name loc tests
        name=$(basename "$d")
        loc=$(count_lines "$d")
        tests=$(count_tests "$d")
        total_loc=$((total_loc + loc))
        total_tests=$((total_tests + tests))
        crate_count=$((crate_count + 1))
        printf '%d\t%d\t%s\n' "$loc" "$tests" "$name" >> "$tmpfile"
    done

    local main_loc main_tests
    main_loc=$(count_lines "$ROOT/src")
    main_tests=$(count_tests "$ROOT/src")
    printf '%d\t%d\t%s\n' "$main_loc" "$main_tests" "src/ (binary)" >> "$tmpfile"

    {
        printf '%s\n' "$WARNING"
        echo "# Project Stats"
        echo ""
        echo "## Overview"
        echo ""
        echo "| Metric | Count |"
        echo "|--------|------:|"
        echo "| Workspace crates | $crate_count |"
        echo "| Lines of Rust (crates/) | $total_loc |"
        echo "| Lines of Rust (src/) | $main_loc |"
        echo "| **Total lines of Rust** | **$((total_loc + main_loc))** |"
        echo "| Tests (crates/) | $total_tests |"
        echo "| Tests (src/) | $main_tests |"
        echo "| **Total tests** | **$((total_tests + main_tests))** |"
        echo ""
        echo "## Crates by size"
        echo ""
        echo "| Crate | Lines | Tests |"
        echo "|-------|------:|------:|"
        sort -t$'\t' -k1 -rn "$tmpfile" | while IFS=$'\t' read -r loc tests name; do
            echo "| \`$name\` | $loc | $tests |"
        done
        echo ""
    } > "$OUT/stats.md"

    rm -f "$tmpfile"
}

# ── crates.md ────────────────────────────────────────────────────────────

generate_crates() {
    {
        printf '%s\n' "$WARNING"
        echo "# Crate Reference"
        echo ""
        echo "Each crate in the \`crates/\` workspace directory."
        echo ""

        for d in "$ROOT"/crates/*/; do
            [ -d "$d/src" ] || continue
            local name desc loc tests
            name=$(basename "$d")
            desc=$(crate_doc "$d")
            loc=$(count_lines "$d")
            tests=$(count_tests "$d")

            echo "## $name"
            echo ""
            [ -n "$desc" ] && echo "$desc" && echo ""
            echo "**${loc}** lines of Rust · **${tests}** tests"
            echo ""

            local deps
            deps=$(workspace_deps "$d")
            if [ -n "$deps" ]; then
                printf '**Workspace deps:** '
                echo "$deps" | sed 's/.*/ `&`/' | paste -sd',' - | sed 's/,/, /g'
                echo ""
                echo ""
            fi

            echo "---"
            echo ""
        done
    } > "$OUT/crates.md"
}

# ── architecture.md ──────────────────────────────────────────────────────

generate_architecture() {
    {
        printf '%s\n' "$WARNING"
        echo "# Architecture Map"
        echo ""
        echo "## Dependency graph"
        echo ""
        echo "Workspace crate dependencies (auto-extracted from Cargo.toml files)."
        echo ""
        echo '```mermaid'
        echo 'graph TD'

        for d in "$ROOT"/crates/*/; do
            [ -d "$d/src" ] || continue
            local name short
            name=$(basename "$d")
            short="${name#clankers-}"
            workspace_deps "$d" | while read -r dep; do
                [ -n "$dep" ] || continue
                local dep_short="${dep#clankers-}"
                echo "    $short --> $dep_short"
            done
        done

        echo '```'
        echo ""
    } > "$OUT/architecture.md"
}

# ── main ─────────────────────────────────────────────────────────────────

echo "generating stats…"
generate_stats

echo "generating crate reference…"
generate_crates

echo "generating architecture map…"
generate_architecture

echo "generated → $OUT/"
